
    create table _user (
        id integer generated by default as identity,
        email varchar(255),
        password varchar(255),
        role varchar(255) check (role in ('USER','ADMIN')),
        username varchar(255) unique,
        primary key (id)
    );

    create table todos (
        user_id integer,
        id bigint generated by default as identity,
        description varchar(255),
        status varchar(255) check (status in ('PENDIENTE','COMPLETADA')),
        title varchar(255),
        primary key (id)
    );

    alter table if exists todos 
       add constraint FKt66d25da3s5etegulsy6vfiij 
       foreign key (user_id) 
       references _user;
