# ==========================================
# CONFIGURACIÓN COMÚN (Para todos los entornos)
# ==========================================
server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://tu-dominio.auth0.com/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /api-docs

---
# ==========================================
# PERFIL: DEV (Tu PC en Windows)
# ==========================================
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://192.168.1.23:5432/tododb
    username: user_admin
    password: password_secure
    driver-class-name: org.postgresql.Driver

---
# ==========================================
# PERFIL: PROD (Jenkins / Docker en Ubuntu)
# ==========================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    # IMPORTANTE: En Docker usamos el nombre del contenedor de la DB
    url: jdbc:postgresql://postgres-db:5432/tododb
    # En Prod usamos las variables que definimos en el Jenkinsfile
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver