# ==========================================
# CONFIGURACIÓN COMÚN
# ==========================================
server:
  port: 8090

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://tu-dominio.auth0.com/

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

---
# ==========================================
# PERFIL: DEV (Windows -> Ubuntu)
# ==========================================
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://192.168.1.23:5432/tododb
    username: user_admin
    password: password_secure
    driver-class-name: org.postgresql.Driver

---
# ==========================================
# PERFIL: PROD (Dentro de Docker en Ubuntu)
# ==========================================
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    # IMPORTANTE: Aquí usamos el hostname definido en el compose
    url: jdbc:postgresql://postgres-db:5432/tododb
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver


